// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxRu_YPDm3xybiNRN9Tsc3MZcnzncDF8Q',
    appId: '1:76439392227:web:697964376f380807ef9ad6',
    messagingSenderId: '76439392227',
    projectId: 'roambot-e1759',
    authDomain: 'roambot-e1759.firebaseapp.com',
    storageBucket: 'roambot-e1759.firebasestorage.app',
    measurementId: 'G-HGNV44N7PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOaQSyFjDdKZu7n94kf_p8-xcgXKq8qt8',
    appId: '1:76439392227:android:2c98dcb2d7d68ff1ef9ad6',
    messagingSenderId: '76439392227',
    projectId: 'roambot-e1759',
    storageBucket: 'roambot-e1759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOoxvd6vPyh3z9XJD7POeaz17t1NFajJ0',
    appId: '1:76439392227:ios:188b6e873b57258eef9ad6',
    messagingSenderId: '76439392227',
    projectId: 'roambot-e1759',
    storageBucket: 'roambot-e1759.firebasestorage.app',
    iosBundleId: 'com.example.roambot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOoxvd6vPyh3z9XJD7POeaz17t1NFajJ0',
    appId: '1:76439392227:ios:188b6e873b57258eef9ad6',
    messagingSenderId: '76439392227',
    projectId: 'roambot-e1759',
    storageBucket: 'roambot-e1759.firebasestorage.app',
    iosBundleId: 'com.example.roambot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxRu_YPDm3xybiNRN9Tsc3MZcnzncDF8Q',
    appId: '1:76439392227:web:af7c59a56eafcc92ef9ad6',
    messagingSenderId: '76439392227',
    projectId: 'roambot-e1759',
    authDomain: 'roambot-e1759.firebaseapp.com',
    storageBucket: 'roambot-e1759.firebasestorage.app',
    measurementId: 'G-ZF6C5F8N9K',
  );
}
